game:GetService("StarterGui"):SetCore("SendNotification",{Title = "皮脚本",Text = "感谢大家一直以来对皮脚本的支持",Icon = "rbxassetid://18941716391",Duration = 1,Callback = bindable,Button1 = "脚本已跑路",Button2 = "感谢您的支持"})
 wait(1.5)
game:GetService("StarterGui"):SetCore("SendNotification",{Title = "皮脚本",Text = "皮脚本于2025.9.20凌晨0点43分 正式停止使用😭😭😭",Icon = "rbxassetid://18941716391",Duration = 1,Callback = bindable,Button1 = "谢谢大家",Button2 = "大家可以去用叶脚本"})
wait(1.5)
game:GetService("StarterGui"):SetCore("SendNotification",{Title = "皮脚本",Text = "希望大家能够记住曾经有一个叫皮脚本的脚本😭",Icon = "rbxassetid://18941716391",Duration = 2,Callback = bindable,Button1 = "最后祝大家生活愉快",Button2 = "再见 我尊贵的皮脚本用户们"})
