return {
    -- 用户名
    ["xiaopi91"] = true,
    ["用户名1"] = true,
    ["用户名2"] = true,
    ["用户名3"] = true,
    ["用户名4"] = true,
    ["用户名5"] = true,
    ["用户名6"] = true,
    ["用户名7"] = true,
    ["用户名8"] = true,
    ["用户名9"] = true,
    ["用户名10"] = true,
    ["用户名11"] = true,
    ["用户名12"] = true,
    ["用户名13"] = true,
    ["用户名14"] = true,
    ["用户名15"] = true,
    ["用户名16"] = true,
    ["用户名17"] = true,
    ["用户名18"] = true,
    ["用户名19"] = true,
    ["用户名20"] = true,
    ["用户名21"] = true,
    ["用户名22"] = true,
    ["用户名23"] = true,
    ["用户名24"] = true,
    ["用户名25"] = true,
    ["用户名26"] = true,
    ["用户名27"] = true,
    ["用户名28"] = true,
    ["用户名29"] = true,
    ["用户名30"] = true,
    ["用户名31"] = true,
    ["用户名32"] = true,
    ["用户名33"] = true,
    ["用户名34"] = true,
    ["用户名35"] = true,
    ["用户名36"] = true,    
    -- HWID
    hwidBlacklist = {
        ["HWID_1"] = true,
        ["HWID_2"] = true,
        ["HWID_3"] = true,
        ["HWID_4"] = true,
        ["HWID_5"] = true,
    }
}
