return {
    -- 用户名
    ["用户名"] = true,
    ["用户名"] = true,
    ["用户名"] = true,
    ["用户名"] = true,
    ["用户名"] = true,
    ["用户名"] = true,
    ["用户名"] = true,
    ["用户名"] = true,
    ["用户名"] = true,
    ["用户名"] = true,
    ["用户名"] = true,
    ["用户名"] = true,
    ["用户名"] = true,
    ["用户名"] = true,
    ["用户名"] = true,
    ["用户名"] = true,
    ["用户名"] = true,
    ["用户名"] = true,
    -- HWID
    ["HWID"] = true,
    ["HWID"] = true,
    ["HWID"] = true,
    ["HWID"] = true,
    ["HWID"] = true,
    ["HWID"] = true,
    ["HWID"] = true,
    ["HWID"] = true,
    ["HWID"] = true,
    ["HWID"] = true,
    ["HWID"] = true,
    ["HWID"] = true,
    ["HWID"] = true,
    ["HWID"] = true,
    ["HWID"] = true,
    ["HWID"] = true,
    ["HWID"] = true,
    ["HWID"] = true,
}
